cookie:
  expiry_days: 5
  key: jncjdjnjddedesaasd
  name: sop_form_cookie
credentials:
  usernames:
    dimitar.i:
      email: mail_dummy@gmail.com
      first_name: "\u0414\u0438\u043C\u0438\u0442\u044A\u0440"
      last_name: "\u0418\u0432\u0430\u043D\u043E\u0432"
      logged_in: false
      password: $2b$12$l3epYKbSDNoS869IgoDqdOf.Grg6UptyvUw92T4r9gyK5D88KeCaa
    elena.p:
      email: mail_dummy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u041F\u0435\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$piAr8qAzwo5S30rbNBdNFumzjDaBSyP67LjIx/Q4JO7Lr./BunR6S
    test01:
      email: ''
      first_name: Test
      last_name: '1'
      logged_in: false
      password: $2b$12$EzPn2iEiNzdU8bLgfOC2O.GmJ4wZtc6nKDzCvR5rsGRQRDpcZjXbC
    test02:
      email: ''
      first_name: Test
      last_name: '2'
      logged_in: false
      password: $2b$12$6GMkojvvgEvz5I/JiTsotOe.13iDRzz9B8y1A5fG/hIrIXB/jJXDO
    test03:
      email: ''
      first_name: Test
      last_name: '3'
      logged_in: false
      password: $2b$12$JKPi7nh5mnOuf/AfUlem1uKbWwYZPGPimKHFiu3s.F/DftQ0gHu8y
    ? ''
    : email: ''
      first_name: ''
      last_name: ' - '
      logged_in: false
      password: $2b$12$1vCgQWcviWK9cr5YJQVZcugd8N0J.6BQ3DSwOYPgziUVal7EklRUa
    zvezdelina.a:
      email: zatanasova2022@gmail.com
      first_name: "\u0417\u0432\u0435\u0437\u0434\u0435\u043B\u0438\u043D\u0430"
      last_name: "\u0410\u0442\u0430\u043D\u0430\u0441\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$UJoRyBmoPWZwc5DDMaucJ.VGtpK.GRPxEhowYBHJyXhTdAMKsRQOe
    raya.s:
      email: rayastefanova915@gmail.com
      first_name: "\u0420\u0430\u044F"
      last_name: "\u0421\u0442\u0435\u0444\u0430\u043D\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$K3.v1qAfmnSWQ/E9B.XMOelr4kr1dDt.J7fXo/p4Lf73.6ikb7u4e
    iliyana.p:
      email: iliyana.popova.psy@gmail.com
      first_name: "\u0418\u043B\u0438\u044F\u043D\u0430"
      last_name: "\u041F\u043E\u043F\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$On4OOfNU6okrFCsifkrC9uZ0V2s.HfcnVEiKvpyD4QqTfn6/CZF4q
    elena.t:
      email: elytodorova.psy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u0422\u043E\u0434\u043E\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$sUw.wSSfP64TYPA2ua7R..LOBsB6I/3pBQLPjokUebRGYR1mkLdYy
    jasmina.d:
      email: jas_d@abv.bg
      first_name: "\u0416\u0430\u0441\u043C\u0438\u043D\u0430"
      last_name: "\u0414\u0438\u043C\u0438\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$m0FbZ9CoaB72MAAMF3fanef0xAtVzoZiEYsnFgVNysCGSXNHu2Knu
    svetlana.a:
      email: svsangelova@gmail.com
      first_name: "\u0421\u0432\u0435\u0442\u043B\u0430\u043D\u0430"
      last_name: "\u0410\u043D\u0433\u0435\u043B\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$nYICTmHjU7lsumQSAeQuHOjkypT1MJ0KS7HOarVk6X7uzN6eLOa5S
    mariya.t:
      email: awsdjf@gmail.com
      first_name: "\u041C\u0430\u0440\u0438\u044F"
      last_name: ''
      logged_in: false
      password: $2b$12$BdRVbAhRjHxhTFGDbmsBHupwujTxgWtpehKLQpAUTH6S4JSrDix4y
    tsveti.p:
      email: asdfg@gmail.com
      first_name: "\u0426\u0432\u0435\u0442\u0438"
      last_name: ' - '
      logged_in: false
      password: $2b$12$fKAGTP9jgeeqWZlvvVXk2O9S0nr/b65HySGW5DtkByPmMQudpT8Pq
