cookie:
  expiry_days: 5
  key: jncjdjnjddedesaasd
  name: sop_form_cookie
credentials:
  usernames:
    dimitar.i:
      email: mail_dummy@gmail.com
      first_name: "\u0414\u0438\u043C\u0438\u0442\u044A\u0440"
      last_name: "\u0418\u0432\u0430\u043D\u043E\u0432"
      logged_in: false
      password: $2b$12$gkYcBO6en3plmbW8NTU0lu..P6CnRgkraEnKJnZzdI8cDFEBgS.ei
    elena.p:
      email: mail_dummy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u041F\u0435\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$dLgNjWUwAo33OSPoNp7K0e.X6lRGJhgmgvyjFPjW0lHBFjQm06I5a
    test01:
      email: ''
      first_name: Test
      last_name: '1'
      logged_in: false
      password: $2b$12$lh0pjbOvfFAlDZ4Ie2Q3NeBl2kyAPElZVBnwTS9S9mlpXLgPq4BI2
    test02:
      email: ''
      first_name: Test
      last_name: '2'
      logged_in: false
      password: $2b$12$yfPys88x.nfCZqEy.B.E8.p6ayJpbRT45UOc9d2Z/I0sjS3T3Fz/m
    test03:
      email: ''
      first_name: Test
      last_name: '3'
      logged_in: false
      password: $2b$12$AjueNWf6RFVZYBTVGE6tKe63jhhDdvPjx.QH4FbUXvCsEzupDx8Zy
    ? ''
    : email: ''
      first_name: ''
      last_name: ' - '
      logged_in: false
      password: $2b$12$rmuQxvQgiWejYk5EMZSas.WJLkgWZjjk43rG.EZIwSriYU4NMP1ku
    zvezdelina.a:
      email: zatanasova2022@gmail.com
      first_name: "\u0417\u0432\u0435\u0437\u0434\u0435\u043B\u0438\u043D\u0430"
      last_name: "\u0410\u0442\u0430\u043D\u0430\u0441\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$E1QQFzR.pXRwCb4kOpoOGu6SmbCu.qkPiSs7aam9kv0teA1SGQXTC
    raya.s:
      email: rayastefanova915@gmail.com
      first_name: "\u0420\u0430\u044F"
      last_name: "\u0421\u0442\u0435\u0444\u0430\u043D\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$peUKStp3oqxBjttWe6gn.ev8/pF6zXdii0Na1tJzmAmP33G6pz8ae
    iliyana.p:
      email: iliyana.popova.psy@gmail.com
      first_name: "\u0418\u043B\u0438\u044F\u043D\u0430"
      last_name: "\u041F\u043E\u043F\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$l32Goj/53dTVhFvrvLhLpuulPEMnWaDiBn5TtW1eYdIkhzDfULGbS
    elena.t:
      email: elytodorova.psy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u0422\u043E\u0434\u043E\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$46DY3lK8/v25wpDIySar8OL1lwai8nITFv8fmR7xQqNrzWRzM5Piu
    jasmina.d:
      email: jas_d@abv.bg
      first_name: "\u0416\u0430\u0441\u043C\u0438\u043D\u0430"
      last_name: "\u0414\u0438\u043C\u0438\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$jbXxrWi4jJ1vZP.fI360U.aivJPpcm7RN4fPXwxRp8o7kct7bs5UO
    svetlana.a:
      email: svsangelova@gmail.com
      first_name: "\u0421\u0432\u0435\u0442\u043B\u0430\u043D\u0430"
      last_name: "\u0410\u043D\u0433\u0435\u043B\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$EElV3abGj3jyMYg64RDgNOWYsNEx4SkEZ4H6c9nOWdJe5g4vfRXKG
