cookie:
  expiry_days: 5
  key: jncjdjnjddedesaasd
  name: sop_form_cookie
credentials:
  usernames:
    dimitar.i:
      email: mail_dummy@gmail.com
      first_name: "\u0414\u0438\u043C\u0438\u0442\u044A\u0440"
      last_name: "\u0418\u0432\u0430\u043D\u043E\u0432"
      logged_in: false
      password: $2b$12$sxncjs8EreDl9KxHMXkdq.Mt97X71fWQOEjHsBQ.4Ri1gPRvznGMa
    gabriela.m:
      email: mail_dummy@gmail.com
      first_name: "\u0413\u0430\u0431\u0440\u0438\u0435\u043B\u0430"
      last_name: "\u041C\u0430\u0440\u0438\u043D\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$HtsFKgpr4uBOhvaK6W561.2IGbn72s.BcCLFhjpNj8uPmMvavJK.i
    elena.p:
      email: mail_dummy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u041F\u0435\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$ZTyr9zroF0OaaQr4O0rGI.bURWFJmF5qaXF9jCOJGx3.G7L6W.WGi
