cookie:
  expiry_days: 5
  key: jncjdjnjddedesaasd
  name: sop_form_cookie
credentials:
  usernames:
    dimitar.i:
      email: mail_dummy@gmail.com
      first_name: "\u0414\u0438\u043C\u0438\u0442\u044A\u0440"
      last_name: "\u0418\u0432\u0430\u043D\u043E\u0432"
      logged_in: false
      password: $2b$12$mDkL/3nM0Xy3cNtoyxg3veLJHaBTONkyJFIA3T8sxTR.D3q8dMUme
    elena.p:
      email: mail_dummy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u041F\u0435\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$JTRVN7Q72XBgVNsjepOOO.MgScvP.rRbYzsFjW87JdfJ7xoWo7P6u
    test01:
      email: ''
      first_name: Test
      last_name: '1'
      logged_in: false
      password: $2b$12$OvxY/h5BYZAkWWyyjkNtkuCjGOld/eg3urqhvn1LrtIqsdR9S4k7O
    test02:
      email: ''
      first_name: Test
      last_name: '2'
      logged_in: false
      password: $2b$12$d7MjjayYuRAlE8xWdF0jhOUjIF8nRcA9QFm6Y3BlzaDeG8tgWRpii
    test03:
      email: ''
      first_name: Test
      last_name: '3'
      logged_in: false
      password: $2b$12$syJkgYYh5mva35qt6rqI0OjhIsP95RMLv.TChT6khfbvjprBkMsyy
    ? ''
    : email: ''
      first_name: ''
      last_name: ' - '
      logged_in: false
      password: $2b$12$nHeBH9AIcxzIHT1MRdspeOHJrxmvMuhvrGENGVVxk4B5lA97PnOeG
    zvezdelina.a:
      email: zatanasova2022@gmail.com
      first_name: "\u0417\u0432\u0435\u0437\u0434\u0435\u043B\u0438\u043D\u0430"
      last_name: "\u0410\u0442\u0430\u043D\u0430\u0441\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$bjllt4YUjUe1e7brHellie32XmrDrrYul1PVH203yRBUSzzXRFecO
    raya.s:
      email: rayastefanova915@gmail.com
      first_name: "\u0420\u0430\u044F"
      last_name: "\u0421\u0442\u0435\u0444\u0430\u043D\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$XVUj1i35ar0V5VUpb56.leP0H1.k3v9WgfmkKT.KfzYq.v25Mn9mq
    iliyana.p:
      email: iliyana.popova.psy@gmail.com
      first_name: "\u0418\u043B\u0438\u044F\u043D\u0430"
      last_name: "\u041F\u043E\u043F\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$M3H3b1xSW/7vZJW149ZEfuSVGCcPz74tOwObdT8oDpmdy//NF/ieO
    elena.t:
      email: elytodorova.psy@gmail.com
      first_name: "\u0415\u043B\u0435\u043D\u0430"
      last_name: "\u0422\u043E\u0434\u043E\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$TVMqJfZVD19AsG6wPaxeTe58z0TTrF4vruuSDfDnfiIYswPhsI0/2
    jasmina.d:
      email: jas_d@abv.bg
      first_name: "\u0416\u0430\u0441\u043C\u0438\u043D\u0430"
      last_name: "\u0414\u0438\u043C\u0438\u0442\u0440\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$qULG1kUHwUv4ABF/Cfu23OGIHzEtRFupn0b3GLmbvhG5sWfmQ6hVm
    svetlana.a:
      email: svsangelova@gmail.com
      first_name: "\u0421\u0432\u0435\u0442\u043B\u0430\u043D\u0430"
      last_name: "\u0410\u043D\u0433\u0435\u043B\u043E\u0432\u0430"
      logged_in: false
      password: $2b$12$djzbr9bnZc81gPHOR2ONeOQ9mo/JoKSg6s0fkHWdeoE5YL9aH0EHu
    mariya.t:
      email: awsdjf@gmail.com
      first_name: "\u041C\u0430\u0440\u0438\u044F"
      last_name: ''
      logged_in: false
      password: $2b$12$p0Kx5xb.DOC.8ujEo51SwuIYNzeV9iT5SvSm.U.lMqyWmuk.9M48O
    tsveti.p:
      email: asdfg@gmail.com
      first_name: "\u0426\u0432\u0435\u0442\u0438"
      last_name: ' - '
      logged_in: false
      password: $2b$12$cxVAd78Y49QFumgNdC/ZDu5AdR1lPbMB2ejw29txl8jUCx0/uPuL6
