# .streamlit/config.toml

# Light and Dark Mode Themes Inspired by Vector Labs Branding

[theme]
# Dark mode theme
primaryColor = "#2fa121"  # Teal accent color consistent with branding
backgroundColor = "#c1eabc"  # Dark teal background
secondaryBackgroundColor = "#ffffff"  # Slightly lighter teal for contrast
textColor = "#000000"  # White text for readability
font = "sans serif"  # Matches light mode for consistency
base = "dark"

